### PR TITLE
Prepare for GTK4: Undepend from libgnomekbd

### PR DESCRIPTION
**Pull request by ZenitsuDev**
Needed as preparation for https://github.com/elementary/switchboard-plug-keyboard/pull/412

### CODE REVIEW

**Comment by ZenitsuDev** [comment]
It spawns gkbd-keyboard-display but it does not output the correct layout. Is there a problem with the layout id being passed? Thanks

**Comment by jeremypw** [comment]
@ZenitsuDev I think you can remove the `libgnomekbd.*` files from the `/vapi` directory?

**Comment by jeremypw** [comment]
@ZenitsuDev I have fixed the problem with displaying the correct layout for you.

**Comment by jeremypw** [comment]
Showing map with AppInfo (in the same way as the Wingpanel) since the previous way caused "not responding" warnings if the dialog was clicked on when the map was open.  Now the map and the dialog are independent.

**Comment by jeremypw** [comment]
At the moment it is possible to show multiple maps (which stay open even after closing the dialog).  I do not think this is a problem but if it is desired to show only one map and prevent the dialog from closing while it is open then additional code will be required.

**Comment by danrabbit** [comment]
Yeah it's slightly less than ideal, but I don't think it's worth spending a lot of time trying to alter it. Seems fine as is to me :+1:

**Review by jeremypw — APPROVED** [review]

**Pull request merged**
