### PR TITLE
Use get_row_at_index

### PR DESCRIPTION
**Pull request by danirabbit**
Can't use `get_children` in GTK4, so use `get_row_at_index` where it makes sense. Use `remove` instead of `destroy` to avoid an infinite loop in GTK 4 where widgets are destroyed but not removed

### CODE REVIEW

**Review by jeremypw — CHANGES_REQUESTED** [review]
I am getting a seg fault at line 150 of Display.vala after adding one input engine to and empty list.
```
hread 1 "io.elementary.s" received signal SIGSEGV, Segmentation fault.
0x00007ffff1928eb4 in keyboard_layout_page_display_rebuild_list (self=0x55555564e6c0) at ../src/Widgets/Layout/Display.vala:150
150	            last_child.down_button.sensitive = false;
(gdb) bt
#0  0x00007ffff1928eb4 in keyboard_layout_page_display_rebuild_list (self=0x55555564e6c0) at ../src/Widgets/Layout/Display.vala:150
#1  0x00007ffff192a94f in keyboard_layout_page_display_constructorPython Exception <class 'gdb.error'>: No type named TypeNode.
 (type=, n_construct_properties=0, construct_properties=0x0) at ../src/Widgets/Layout/Display.vala:83
#2  0x00007ffff7c4a31e in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#3  0x00007ffff7c4b34d in g_object_new_with_properties () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007ffff7c4be51 in g_object_new () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007ffff1928f45 in keyboard_layout_page_display_constructPython Exception <class 'gdb.error'>: No type named TypeNode.
 (object_type=) at ../src/Widgets/Layout/Display.vala:21
#6  0x00007ffff1928f64 in keyboard_layout_page_display_new () at ../src/Widgets/Layout/Display.vala:21
#7  0x00007ffff19359ca in keyboard_layout_page_page_constructorPython Exception <class 'gdb.error'>: No type named TypeNode.
 (type=, n_construct_properties=0, construct_properties=0x0) at ../src/Views/Layout.vala:26
#8  0x00007ffff7c4a31e in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007ffff7c4b34d in g_object_new_with_properties () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff7c4be51 in g_object_new () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff1935416 in keyboard_layout_page_page_constructPython Exception <class 'gdb.error'>: No type named TypeNode.
 (object_type=) at ../src/Views/Layout.vala:6

```

**Comment by danirabbit** [comment]
@jeremypw ah I didn't realize this list didn't reflect the same number of items in the list. We can use `observe children` in GTK 4, but docs say it's expensive. So I'm avoiding the list here unless we need it

**Comment by jeremypw** [comment]
@danirabbit  You could try:
```
        int index = 0;
        while (list.get_row_at_index (index) != null) { index++; }
        unowned var first_child = (DisplayRow) list.get_row_at_index (0);
        unowned var last_child = first_child;
        if (index > 1) {
             last_child = (DisplayRow) list.get_row_at_index (index - 1);
        }

        first_child.up_button.sensitive = false;
        last_child.down_button.sensitive = false;
```

**Comment by danirabbit** [comment]
@jeremypw ah yeah you're smart. It's probably plenty cheap enough to just iterate every time for a list that's probably pretty short

**Comment by jeremypw** [comment]
Yes. Tbh `observe_children ()` is probably not that expensive for short lists.  But we can go with this for now.

**Review by jeremypw — APPROVED** [review]

**Pull request merged**
