### PR TITLE
Custom Shortcuts: New add/remove list pattern

### PR DESCRIPTION
**Pull request by lenemter**
image

### CODE REVIEW

**Comment by jeremypw** [comment]
@lenemter Could you add some reasons for these changes to assist review?  Thanks.

**Comment by lenemter** [comment]
@jeremypw IMO the current way of deleting custom shorcuts is inconvinient. I think that most users expect a "Remove" button in gear menu, but instead they have to select the shortcut and press the "-" button at the very bottom of the list

**Review by danrabbit — APPROVED** [review]
Yeah this looks good. Uses the more modern pattern we've been switching to for adding and removing list rows and cleans up the code significantly. Nice work :+1:

**Comment by lenemter** [comment]
I think i forgot to make "Add Shortcut" translatable

**Pull request merged**
