### PR TITLE
Add reinstall instruction to readme

### PR DESCRIPTION
**Pull request by peteruithoven**

### CODE REVIEW

**Comment by peteruithoven** [comment]
It isn't a weird thing to want to know right? You want to try something, but then you also want to know how to go back to the regular version.

**Comment by donadigo** [comment]
Hm, yes, you're right. Please add a "(Ubuntu-based systems)" to the tiltle of this section then. Anyway, it's up to the team.

**Comment by peteruithoven** [comment]
Shouldn't that be "(Debian-based systems)"?

**Comment by danrabbit** [comment]
I agree with Adam, this is an operation that is specific to your distro and package manager and doesn't really have anything to do with this codebase. Closing as "Won't Fix"

**Pull request closed without merging**
