### PR TITLE
Add icons to shortcuts sections

### PR DESCRIPTION
**Pull request by danrabbit**
There's probably a better way to do this in the future, but at least this does it the same way as the names

screenshot from 2018-02-26 09 17 05

### CODE REVIEW

**Comment by artemanufrij** [comment]
@danrabbit what do you think about handle it in `Group` struct? We could add two new properties `icon_name`, and `group_name` and fill it in `List.vala`. In `SectionSwitcher.vala` we would just read it out and fill `label` and `image` objects.

and we could remove `section_icons` and `section_names`

**Comment by danrabbit** [comment]
@artemanufrij Yeah I think that makes sense to define the section name and icon in the same place as we create the section :+1:

**Comment by artemanufrij** [comment]
@danrabbit would you push the changes in this pr or in a new one?

**Comment by danrabbit** [comment]
Same PR is probably fine here

**Pull request merged**
