### PR TITLE
Fix Pane Width (#11)

### PR DESCRIPTION
**Pull request by Skyus**
This addresses #11 by just making the abstract page column homogeneous.

I believe this is the cleanest solution, really...

### CODE REVIEW

**Comment by danrabbit** [comment]
This is not really an optimal solution. The proper way to do this is probably to use a Gtk.SizeGroup

**Comment by Skyus** [comment]
I did try a SizeGroup but could not get it to work. Guess I'll give it another shot this weekend.

**Comment by Skyus** [comment]
Okay so as it turns out I just did not make the Advanced Settings panel homogeneous as well. So that is that. (Tested with UK English, Japanese)

I think I'll still try SizeGroups again later, but I haven't had too much luck with them last time.

**Comment by jeremypw** [comment]
From Sizegroup documentation:

"_SizeGroup provides a mechanism for grouping a number of widgets together so they all request the same amount of space. This is typically useful when you want a column of widgets to have the same size, but you can’t use a GtkGrid widget._"

Since the widgets of concern are in grids it seems to me the better solution to use the _homogenous_  property as has been done.

**Comment by danrabbit** [comment]
screenshot from 2017-10-20 17 47 33

This has unintended side effects

**Comment by Skyus** [comment]
Are they numerous enough to warrant doing away with Gtk.Grid's sizing system altogether though? It might be better to just fix them...

**Comment by jeremypw** [comment]
The homogeneous property should be set in the creator of the derived classes not in the abstract class since derived classes may have different needs.

**Comment by Skyus** [comment]
Well, @danrabbit went ahead and removed any reference to homogeneity in the AbstractPage so I just added it for the two pages. ~~I genuinely like that smaller behavior page though~~

**Pull request merged**
