### PR TITLE
Remove entries for hardcoded GNOME apps

### LINKED ISSUE #60: Calculator keyboard shortcut doesn't work
Go into the keyboard shortcuts, and create one for the calculator under "Applications". It won't ever work, even though other app shortcuts seem to work fine. This seems distinct from, but may relate to:

https://bugs.launchpad.net/elementaryos/+bug/1411557

Launchpad Details: [#LP1562708](https://bugs.launchpad.net/bugs/1562708) Bob Meyers - 2016-03-28 06:38:15 +0000

### PR DESCRIPTION
**Pull request by danrabbit**
Fixes #60 

It appears these app entries are hardcoded to GNOME apps/features in the media keys plugin and can't be configured.

### CODE REVIEW

**Comment by jeremypw** [comment]
Is it not possible for our apps to register with the relevant Dbus service (haven't looked into the details)?  However, I guess that while it does not work it is best removed from here.

**Comment by jeremypw** [comment]
Another workaround is to link "gnome-calculator.desktop" to "io.elementary.calculator.desktop".

**Comment by danrabbit** [comment]
Yeah I dug around for a while but I couldn't see how it could be configured. It looks like the .desktop names are actually harcoded for calculator. For other apps it can look up the default from mime or URL handling.

I thought about the symlink but that would create a packaging conflict for someone that wanted to actually install gnome calculator :/

**Comment by jeremypw** [comment]
Installing gnome-calculator just overwrites the symlink.  However, uninstalling gnome-calculator again would not restore the link so the shortcut would stop working (until reinstalling elementary calculator anyway)

**Pull request merged**
