### PR TITLE
Plug search fixes

### PR DESCRIPTION
**Pull request by peteruithoven**
Alterations to get better results when searching for sub settings. See: https://github.com/elementary/applications-menu/pull/133

### CODE REVIEW

**Comment by danrabbit** [comment]
Hm I'm not sure this would necessarily yield better results. I think if we did this in all plugs we'd probably end up with more erroneous results since a string like "Behavior" is something that many different kinds of settings could potentially  have

**Comment by peteruithoven** [comment]
Good point. 
But the difference it makes sure that with elementary/applications-menu#133 we get:
screenshot from 2018-10-03 00 07 49

Instead of:
screenshot from 2018-10-03 00 10 18

This is one of those downsides of using `search` for this purpose. 

I could change how searching sub settings work, but I still need the human readable page/view/sub_setting name. Unless we don't want to refer the user to the page name.

**Comment by danrabbit** [comment]
I'm not sure that's an improvement. I think we want to direct users towards specific results, not titles of pages

**Comment by cassidyjames** [comment]
@peteruithoven I think the issue I'm seeing now is that with the de-duping from https://github.com/elementary/applications-menu/pull/133, this actually gives me less relevant results. For example, before I could search for, "caps" and get the Caps Lock result for keyboard settings. With this PR, I no longer get that.

**Comment by peteruithoven** [comment]
Fair points. 

There are a lot of things I could improve on how I did https://github.com/elementary/applications-menu/pull/133. 

In regards to filtering the results:
I could include the all the levels, don't de-dup based on view, but that might add a lot of extra potential results, see the list at: https://github.com/elementary/applications-menu/issues/94#issuecomment-425161136
Example with most of my filtering removed and this PR:
screenshot from 2018-10-03 01 52 37

On top of that I could also tweak how the matching works, so that we don't get all the sub settings when searching on "keyboard" for example, by matching only on the last level.

**Comment by cassidyjames** [comment]
Yeah, dumping _everything_ there is probably not the best, but I do wonder if the last level would be sufficient. 

For example, searching "compose" could come up with Mail's "Compose Message" action and the "Keyboard → Layout → Compose Key", but searching "keyboard" could come up with IBus, Onboard, and the top-level "Keyboard" settings result. It means you can't use that simple query for discovery, but I think that's fine as this is a precise search context more than a broad discovery one.

**Comment by peteruithoven** [comment]
@cassidyjames I've implemented something like that in this PR: https://github.com/elementary/applications-menu/pull/142

**Comment by danrabbit** [comment]
Not gonna hit "Merge" on this just yet since it looks like we're still waiting for a stable Juno release

**Pull request merged**
