### PR TITLE
Layout: allow to set a custom shortcut to switch layouts

### LINKED ISSUE #472: Free up the `Super` key
I would like to change the keyboard layout using `Super Space` combination.

Please make available

### PR DESCRIPTION
**Pull request by lenemter**
Fixes #472

image

A lot of changes were required to embed the list from shortcuts tab, so I'll try to propose a cleanup branch later to reduce the diff.

### CODE REVIEW

**Comment by TomiOhl** [comment]
> * Uses radio buttons inside flowboxes instead of combo boxes

I know there were some moves to the same direction in some plugs but personally I find this pretty overwhelming to look at.

**Comment by lenemter** [comment]
@TomiOhl I agree,  I had an idea to use plain lists of radio buttons, but it takes too much vertical space. So I reverted it back to using combo boxes.

**Comment by danirabbit** [comment]
Good call reverting back to comboboxes. When there's only a handful of options I think radiobuttons are usually a little nicer for being able to see and compare the available options, but in this case there's just so many options that it's really overwhelming and it makes it actually more difficult to see what your overall settings actually are.

I definitely think it's cool to have this be a more open-ended keyboard shortcut like others are, but I'm not sure about the "additional shortcut" setting here. It seems weird to have a duplicate between a custom shortcut and a list of options and like just having the custom shortcut would satisfy everyone here.

This also makes me think that maybe these options should be in Shortcuts → System instead of in the Layout tab and we could link from the Layout tab to the Shortcuts tab to help discovery here. Thoughts on that?

**Comment by lenemter** [comment]
> just having the custom shortcut would satisfy everyone here

No, it wouldn't.
1) You can't set custom accelerators-only shortcuts (like Alt + Shift or Ctrl + Alt)
2) Caps Lock is a common shortcut to change layouts but original action doesn't get disabled when setting it as a custom keyboard shortcut
3) Even if wanted to remove "Additional shortcut" (like Gnome did) we will have to wait for OS 8, because people have it set and we can't just remove it.

**Comment by lenemter** [comment]
> This also makes me think that maybe these options should be in Shortcuts → System instead of in the Layout tab and we could link from the Layout tab to the Shortcuts tab to help discovery here. Thoughts on that?

I don't like this idea because it's not convenient. Why put it in Shortcuts → System if we can put it closer to related settings?

**Comment by danirabbit** [comment]
> > This also makes me think that maybe these options should be in Shortcuts → System instead of in the Layout tab and we could link from the Layout tab to the Shortcuts tab to help discovery here. Thoughts on that?
> 
> I don't like this idea because it's not convenient. Why put it in Shortcuts → System if we can put it closer to related settings?

I'm thinking of in the future where #18 is solved and that it would be easy to have a discovery path from this tab to the shortcuts tab by adding a link, but it would be harder if someone went to the shortcuts tab first to point them back to this tab to look for the setting

**Pull request closed without merging**
